server:
  port: ${PORT:8077}

spring:
  application:
    name: rabbit-sub-config-poc
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:provisioner}
    password: ${RABBITMQ_PASSWORD:provisioner}
  docker:
    compose:
      lifecycle-management: start_and_stop
app:
  security:
    api-key: poc-secret-api-key
  queue:
    prefix: "proxy."
    exchange: proxy.topic

logging:
  level:
    com.czertainly.rabbitmq.bootstrap: DEBUG
    org.springframework.amqp: INFO
